# Hi there 👋 
My name is Jethro Lopwus A Highly skilled and versatile Software Developer with extensive experience in full-stack development, specializing in frontend technologies like JavaScript, React.js, and Next.js, and backend development using Node.js. Also  expertise in blockchain development with  Solidity, Cairo, Go (Golang), and Rust.
Adept at designing, developing, and deploying scalable, secure, and high-performance web applications and decentralized systems.
Passionate about leveraging cutting-edge technologies to solve complex problems and deliver innovative solutions.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
